version: "3.9"
services:
  olivia_docker:
    image: olivia:v1
    container_name: "olivia_ubuntu"
    volumes:
      - olivia_volume:/workspaces
      - /c/docker_sync:/sync-workspace
      - /dev:/dev
    network_mode: "host"
    tty: true

volumes:
  olivia_volume:
    external: true